### ISSUE TITLE
Jsonschema validation 4 to 5 times slower when upgrading to referencing 0.31.0

### ISSUE THREAD

**Issue by riadhelloumi** [python-jsonschema/referencing#103]
Hello,

We are using intensively jsonschema to validate the schema of internal documents. jsonschema uses referencing to resolve some json references.

Our Python script is spending 99,99% of the time looping over a function like:
`jsonschema.validate(dictionary, schema)`

When running with referencing 0.30.2, we timed the Python script (with time command):

`13.49user 0.07system 0:13.58elapsed 99%CPU (0avgtext+0avgdata 54936maxresident)k
0inputs+16outputs (0major+15239minor)pagefaults 0swaps`

When upgrading to referencing 0.31.0, we timed:
`56.42user 0.12system 0:56.60elapsed 99%CPU (0avgtext+0avgdata 55364maxresident)k
0inputs+16outputs (0major+17380minor)pagefaults 0swaps`

Could you help to understand why the Python script is 4 to 5 times slower when moving to referencing 0.31.0 ?

Best regards,
Riadh

**Comment by Julian** [comment]
Hi there, you haven't really provided any information here unfortunately, I'd need to see something which reproduces whatever you're reporting. That's especially so given there are absolutely no functional changes between referencing 0.30.2 and 0.31.0 (a release which essentially did nothing but remove `type: ignore` comments).

(Calling `jsonschema.validate` repeatedly with the same schema over and over again is also suspicious sounding if that's what you're doing. See the docs for details on instead creating a `Validator` instance.)

**Comment by riadhelloumi** [comment]
Hi Juilan,
Thank you, your comment helped a lot to optimize my code with Validator.
Best regards,
Riadh
