### ISSUE TITLE
Are relative JSON pointers supported?

### ISSUE THREAD

**Issue by Viicos** [python-jsonschema/referencing#125]
Sorry it's me again :smile: 

I'm making some progress on my "schema walker" experiments, and wanted to see how relative references using [relative JSON pointers](https://json-schema.org/draft/2020-12/relative-json-pointer) were handled.

The docstring of the `Resolver` class states:

https://github.com/python-jsonschema/referencing/blob/7d6069a7dfa76be679b02587b1ba89a0bfe7348d/referencing/_core.py#L615-L621

However, trying with the following example (and making use of the `jsonschema` library for demonstration purposes), I get the following:

```python
from jsonschema.validators import Draft7Validator

schema = {
    "$id": "my_schema",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "first_email": {
            "type": "string",
            "format": "email"
        },
        "second_email": {
            "$ref": "1/first_email"
        }
    }
}

Draft7Validator(alt).validate({"first_email": "a@example.com", "second_email": "b@example.com"})
```

I couldn't find anything in the codebase that would handle these relative JSON pointers. I'm also unsure when this was introduced in the json schema spec(s), I couldn't find anything in the changelogs. Thanks in advance!

**Comment by Julian** [comment]
Hi!

That isn't a valid JSON Schema (and this library of course only deals with references which are valid JSON Schema).

"Relative" in that docstring meant "relative URI" not "relative JSON Pointer" which is what you have there, albeit of course it'd be nice to clarify that there.

More specifically the `$ref` keyword in all current dialects of JSON Schema does not take a relative JSON pointer. The JSON Schema spec does reference the relative JSON pointer spec, but IIRC just to allow keywords to define things in terms of them, and to have a `format: relative-json-pointer` format. It does not define any of its own "official dialect keywords" to take relative pointers.

It probably *would* be nice to have such referencing support here at some point but the initial focus was certainly only on existing JSON Schema dialects.

**Comment by Viicos** [comment]
Interesting! Got misled by [this example](https://opis.io/json-schema/2.x/pointers.html#relative-pointers), reading more about it Opis seems to extand the json schema specification to allow relative pointers. Thanks again
