### ISSUE TITLE
RefResolver (or its successor) should allow customizing deserialization, not only scheme / retrieval

### ISSUE THREAD

**Issue by martingkelly** [python-jsonschema/referencing#4]
I'm using currently handling schemas written in YAML (for human-readability) but validated by jsonschema. I parse the schema in YAML (and make sure I subset my YAML to stay JSON-compatible) and then run the parsed dictionary through jsonschema. It is working nicely with one issue: When I want to use file:// includes, the files are implicitly assumed to be json.

@Julian I would like to add support for these files being YAML and am wondering if this is something you would support. If so, what is your recommendation for the cleanest way to add it? If it's not something you support, what would you recommend as the cleanest way to add the support for my own code without hacking/forking jsonschema? I thought about adding custom resolver as is done in https://github.com/Julian/jsonschema/issues/225, but it sounds like `RefResolver` is not intended to be API-stable, so subclassing is liable to break in the future. Is there another way?

Thanks,
Martin

**Comment by Julian** [comment]
Hello there!

This, along with many many other `$ref`-related issues, is now finally being handled in python-jsonschema/jsonschema#1049 with the introduction of this new [referencing library](https://github.com/python-jsonschema/referencing/) which is fully compliant and has APIs which I hope are a lot easier to understand and customize. (At some point recently I'd transferred this issue to the issue tracker for referencing, in case that wasn't clear).

The next release of `jsonschema` (v4.18.0) will contain a merged version of that PR, and should be released shortly in beta, and followed quickly by a regular release, assuming no critical issues are reported.

Dereferencing YAML, TOML, or whatever else is definitely doable using `referencing`. If you still care to, I'd love it if you tried out the beta once it is released, or certainly it'd be hugely helpful to immediately install the branch containing this work (https://github.com/python-jsonschema/jsonschema/tree/referencing) and confirm. You can in the interim find documentation for the change in a [preview page here](https://python-jsonschema--1049.org.readthedocs.build/en/1049/referencing/). A section specifically on resolving YAML is [here](https://python-jsonschema--1049.org.readthedocs.build/en/1049/referencing/#resolving-references-to-schemas-written-in-yaml) and can be combined of course with the example shown there on retrieving remote resources over HTTP if so desired.

I'm going to close this given it indeed seems like it is addressed by python-jsonschema/jsonschema#1049, but feel free to follow up with any comments. Sorry for the delay in getting to these, but hopefully this new release will bring lots of benefit!
