### ISSUE TITLE
RFE: merge python-jsonschema/referencing-suite into python-jsonschema/referencing?🤔 

### ISSUE THREAD

**Issue by kloczek** [python-jsonschema/referencing#52]
Looks like `refferencing` module uses external git submodule https://github.com/python-jsonschema/referencing-suite.

If that submodules is not used anywhere else (so far I was not able to find that is used by some other modules) probably it would be good to merge python-jsonschema/referencing-suite directly into python-jsonschema/referencing test suite.

**Comment by Julian** [comment]
No, the two are separate projects, with the suite being language agnostic.
