### ISSUE TITLE
Cannot pip install on alpine - maybe prebuilt version missing?

### ISSUE THREAD

**Issue by jonaslb** [python-jsonschema/referencing#54]
The following fails on alpine: `pip install referencing`.

In fairness, the problem is with the `rpds-py` package, but I could not find a separate issue tracker for that, it seems to only exist for the purpose of this project, so I am posting it here instead.

I originally ran into this problem using Poetry in CI on Alpine (which depends on jsonschema, which depends on this).

I think maybe a "musllinux" build is missing?

In full it can be reproduced in a small example like this:

```sh
docker run --rm -it alpine:3.18
apk add python3 py-pip
pip install referencing
```

Which gives the output:

```
Collecting referencing
  Using cached referencing-0.29.1-py3-none-any.whl (25 kB)
Collecting attrs>=22.2.0 (from referencing)
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting rpds-py>=0.7.0 (from referencing)
  Using cached rpds_py-0.7.1.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Julian** [comment]
The issue tracker is [here](https://github.com/crate-py/rpds/).

And essentially that error is saying your container needs a rust toolchain -- indeed musl wheels would obviate that need but I haven't yet figured out how to build them with maturin. A PR is certainly welcome there.

Going to close this since it duplicates crate-py/rpds#6 which is essentially about the same thing, but yeah help welcome!
