### ISSUE TITLE
TypeError: field() got an unexpected keyword argument 'alias'

### ISSUE THREAD

**Issue by gokceneraslan** [python-jsonschema/referencing#56]
Hi,

I am using nbconvert to convert Jupyter notebooks to RST files in my project and getting the following jsonschema/referencing exception during the build process:

```pytb
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/nbconvert/filters/markdown.py", line 13, in <module>
    from .markdown_mistune import markdown2html_mistune
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/nbconvert/filters/markdown_mistune.py", line 22, in <module>
    from nbconvert.filters.strings import add_anchor
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/nbconvert/filters/strings.py", line 23, in <module>
    from nbconvert.preprocessors.sanitize import _get_default_css_sanitizer
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/nbconvert/preprocessors/__init__.py", line 3, in <module>
    from nbclient.exceptions import CellExecutionError
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/nbclient/__init__.py", line 5, in <module>
    from .client import NotebookClient, execute  # noqa: F401
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/nbclient/client.py", line 17, in <module>
    from nbformat import NotebookNode
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/nbformat/__init__.py", line 11, in <module>
    from . import v1, v2, v3, v4
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/nbformat/v4/__init__.py", line 23, in <module>
    from .convert import downgrade, upgrade
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/nbformat/v4/convert.py", line 11, in <module>
    from nbformat import v3, validator
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/nbformat/validator.py", line 16, in <module>
    from .json_compat import ValidationError, _validator_for_name, get_current_validator
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/nbformat/json_compat.py", line 11, in <module>
    import jsonschema
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/jsonschema/__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/jsonschema/_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/jsonschema/exceptions.py", line 14, in <module>
    from referencing.exceptions import Unresolvable as _Unresolvable
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/referencing/__init__.py", line 4, in <module>
    from referencing._core import Anchor, Registry, Resource, Specification
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/referencing/_core.py", line 29, in <module>
    class Specification(Generic[D]):
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/referencing/_core.py", line 55, in Specification
    ] = field(alias="anchors_in")
TypeError: field() got an unexpected keyword argument 'alias'
Exception occurred:
  File "/builds/group/myproject/.tox/docs/lib/python3.8/site-packages/referencing/_core.py", line 55, in Specification
    ] = field(alias="anchors_in")
TypeError: field() got an unexpected keyword argument 'alias'
```

I am clueless about why this might be happening and appreciate any help. Thank you.

**Comment by gokceneraslan** [comment]
Versions of all packages installed by tox:

accelerate==0.20.3,aiohttp==3.8.4,aiosignal==1.3.1,alabaster==0.7.13,anndata==0.9.1,appdirs==1.4.4,argcomplete==3.1.1,argh==0.28.1,arrow==1.2.3,asttokens==2.2.1,async-timeout==4.0.2,attrs==21.4.0,Babel==2.12.1,backcall==0.2.0,backports.zoneinfo==0.2.1,beautifulsoup4==4.12.2,binaryornot==0.4.4,bioframe==0.4.1,biopython==1.81,biothings-client==0.3.0,bleach==6.0.0,bpnet-lite==0.5.1,captum==0.5.0,certifi==2023.5.7,chardet==5.1.0,charset-normalizer==3.2.0,click==8.1.4,cmake==3.26.4,colorama==0.4.6,colorlog==6.7.0,contourpy==1.1.0,cookiecutter==2.2.0,coverage==7.2.7,cycler==0.11.0,decorator==5.1.1,defusedxml==0.7.1,deprecation==2.1.0,discrete-key-value-bottleneck-pytorch==0.0.8,diskcache==5.6.1,docker-pycreds==0.4.0,docutils==0.20.1,einops==0.6.1,enformer-pytorch==0.7.6,exceptiongroup==1.1.2,executing==1.2.0,fastjsonschema==2.17.1,filelock==3.12.2,fonttools==4.40.0,frozenlist==1.3.3,fsspec==2023.6.0,furo==2023.5.20,future==0.18.3,genomepy==0.16.1,gffutils==0.12,gitdb==4.0.10,GitPython==3.1.31,h5py==3.9.0,hdf5plugin==4.1.3,huggingface-hub==0.16.4,idna==3.4,igraph==0.9.11,imagesize==1.4.1,importlib-metadata==6.8.0,importlib-resources==6.0.0,iniconfig==2.0.0,ipython==8.12.2,jedi==0.18.2,Jinja2==3.1.2,joblib==1.3.1,jsonschema==4.18.0,jsonschema-specifications==2023.6.1,jupyter_client==8.3.0,jupyter_core==5.3.1,jupyterlab-pygments==0.2.2,kipoi==0.8.6,kipoi-conda==0.3.1,kipoi-utils==0.7.7,kipoiseq==0.7.1,kiwisolver==1.4.4,leidenalg==0.8.10,lightning-utilities==0.9.0,lit==16.0.6,llvmlite==0.40.1,logomaker==0.8,loguru==0.7.0,MarkupSafe==2.1.3,matplotlib==3.7.2,matplotlib-inline==0.1.6,mistune==3.0.1,mizani==0.9.2,modisco-lite==2.2.0,MOODS-python==1.9.4.1,mpmath==1.3.0,multidict==6.0.4,mygene==3.2.2,mysql-connector-python==8.0.33,natsort==8.4.0,nbclient==0.8.0,nbconvert==7.6.0,nbformat==5.9.0,nbsphinx==0.9.2,ncls==0.0.68,networkx==3.1,nltk==3.8.1,norns==0.1.6,nose==1.3.7,numba==0.57.1,numpy==1.24.4,nvidia-cublas-cu11==11.10.3.66,nvidia-cuda-cupti-cu11==11.7.101,nvidia-cuda-nvrtc-cu11==11.7.99,nvidia-cuda-runtime-cu11==11.7.99,nvidia-cudnn-cu11==8.5.0.96,nvidia-cufft-cu11==10.9.0.58,nvidia-curand-cu11==10.2.10.91,nvidia-cusolver-cu11==11.4.0.1,nvidia-cusparse-cu11==11.7.4.91,nvidia-nccl-cu11==2.14.3,nvidia-nvtx-cu11==11.7.91,packaging==23.1,pandas==2.0.3,pandocfilters==1.5.0,parso==0.8.3,pathtools==0.1.2,patsy==0.5.3,pexpect==4.8.0,pickleshare==0.7.5,Pillow==10.0.0,pip==23.1.2,pkgutil_resolve_name==1.3.10,platformdirs==3.8.1,plotnine==0.12.1,pluggy==1.2.0,polars==0.18.6,prompt-toolkit==3.0.39,protobuf==3.20.3,psutil==5.9.5,ptyprocess==0.7.0,pure-eval==0.2.2,pyBigWig==0.3.22,pyfaidx==0.7.2.1,Pygments==2.15.1,pyparsing==3.0.9,pyranges==0.0.129,pytest==7.4.0,pytest-cov==4.1.0,python-dateutil==2.8.2,python-slugify==8.0.1,pytorch-lightning==1.9.5,pytz==2023.3,PyYAML==6.0,pyzmq==25.1.0,referencing==0.29.1,regex==2023.6.3,related==0.7.3,requests==2.31.0,rpds-py==0.8.8,safetensors==0.3.1,scikit-learn==1.3.0,scipy==1.10.1,seaborn==0.12.2,sentry-sdk==1.27.1,setproctitle==1.3.2,setuptools==67.8.0,simplejson==3.19.1,six==1.16.0,smmap==5.0.0,snowballstemmer==2.2.0,sorted-nearest==0.0.39,soupsieve==2.4.1,Sphinx==7.0.1,sphinx-basic-ng==1.0.0b1,sphinxcontrib-applehelp==1.0.4,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.1,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,stack-data==0.6.2,statsmodels==0.14.0,sympy==1.12,tabulate==0.9.0,text-unidecode==1.3,texttable==1.6.7,threadpoolctl==3.1.0,tinycss2==1.2.1,tinydb==4.8.0,tokenizers==0.13.3,tomli==2.0.1,torch==2.0.1,torchmetrics==1.0.0,tornado==6.3.2,tqdm==4.65.0,traitlets==5.9.0,transformers==4.30.2,triton==2.0.0,typing_extensions==4.7.1,tzdata==2023.3,urllib3==2.0.3,vector-quantize-pytorch==1.6.28,wandb==0.15.5,wcwidth==0.2.6,webencodings==0.5.1,wheel==0.40.0,yarl==1.9.2,zipp==3.15.0 

When I look at the logs of successful doc builds, I see jsonschema v4.17.3 was working well, but it is broken when jsonschema 4.18 + referencing are used, fyi

**Comment by gokceneraslan** [comment]
OK I think this happened because I had a dependency which requires `attrs<=21.4.0` (https://github.com/kipoi/kipoi/blob/master/setup.py#L29) but the `alias` keyword argument of `field` in the attrs package was introduced in attrs 22.2.0 (https://github.com/python-attrs/attrs/releases/tag/22.2.0, hence the attrs>=22.2.0 dependency of the referencing package). I will somehow make sure that attrs>=22.2.0 is installed in the documentation build environment :)

**Comment by WardBrian** [comment]
I just ran into this error despite having `attrs>=22.2.0`. The only way I was able to resolve it and get `jupyter` working was by installing jsonschema < 4.18.0 and removing the `referencing` library

**Comment by spott** [comment]
I just ran into this error as well despite having `attrs` 23.1.0.

It is rather annoying, as I can't get Jupyter working.

**Comment by ragnarov** [comment]
no fix yet?

**Comment by Julian** [comment]
There's nothing broken in this package, this error results from user installation error. If you share a reproducible errorin a discussion someone may be able to point out what to do.

**Comment by HaleyBG** [comment]
I have solved it by updating the attrs package in the base environment.
