### ISSUE TITLE
Type annotations for `Registry` usage are not well-supported by `mypy`, slightly tricky with `pyright`

### ISSUE THREAD

**Issue by sirosen** [python-jsonschema/referencing#61]
I'm finally back to taking some time to work on updating `check-jsonschema` to use `jsonschema>=4.18` with `referencing`!

The only issue I've really had so far is that the type annotations are not as straightforward to satisfy as I would like.
The `attrs`-derived initializers are not understood by `mypy` as well as they are for `pyright`, and `pyright` is being a bit "fussy" about type invariance.
There's a cluster of related problems to work out, but I think my main item is the failure under `mypy`. This seems like a deficiency of `mypy`, since `pyright` works, but it may be a deficiency which is easy enough to be worth accommodating; I don't know yet.

Here's a simplified version of my registry builder, `resolver_simple.py`:
```python
from __future__ import annotations

import referencing
import requests
from referencing.jsonschema import DRAFT202012, Schema

def retrieve_reference(uri: str) -> referencing.Resource[Schema]:
    data = requests.get(uri, stream=True).json()
    return referencing.Resource.from_contents(data, default_specification=DRAFT202012)

def make_reference_registry(
    schema_uri: str | None, schema: dict
) -> referencing.Registry:
    schema_resource = referencing.Resource.from_contents(
        schema, default_specification=DRAFT202012
    )
    registry = referencing.Registry(retrieve=retrieve_reference)

    # aside: I'm not 100% sure these next parts are correct
    # schemas with no explicit `$id` are inherently ambiguous
    # but it would be nice to support using the URI from whence we retrieved them
    if schema_uri is not None:
        registry = registry.with_resource(uri=schema_uri, resource=schema_resource)

    id_attribute = schema.get("$id")
    if id_attribute is not None:
        registry = registry.with_resource(uri=id_attribute, resource=schema_resource)

    return registry
```

`mypy` doesn't understand that `retrieve` is an `attrs`-provided field:
```
$ mypy resolver_simple.py                                   
resolver_simple.py:19: error: Unexpected keyword argument "retrieve" for "Registry"  [call-arg]
resolver_simple.py:19: error: Need type annotation for "registry"  [var-annotated]
Found 2 errors in 1 file (checked 1 source file)
```

By contrast, pyright likes this file and gives it a pass. Which makes my next example a little bit of a headscratcher at first.

The real implementation makes parsing a bit more pluggable, for which I have a simple object, `ParserSet`. As a result, `retrieve` is built dynamically, and the resulting type somehow mismatches under `pyright`. It looks something like this:
```python
def create_retrieve_callable(
    parsers: ParserSet,
) -> typing.Callable[[str], referencing.Resource[Schema]]:
    def retrieve_reference(uri: str) -> referencing.Resource[Schema]:
        data = requests.get(uri, stream=True)
        parsed_object = parsers.parse(data.raw, uri)

        return referencing.Resource.from_contents(
            parsed_object, default_specification=DRAFT202012
        )

    return retrieve_reference
```
which results in a pyright error like
```
error: Argument of type "(str) -> Resource[Schema]" cannot be assigned to parameter "retrieve" of type "Retrieve[D@Registry]" in function "__init__"
    Type "(str) -> Resource[Schema]" cannot be assigned to type "(uri: URI) -> Resource[Schema]"
```

After staring at the error output long enough, I realized that `pyright` is picky about this because that `Callable` type doesn't specifically have the signature `def f(uri: str) -> referencing.Resource[Schema]: ...`. `f` here takes `uri` as a keyword-or-positional -- something which `Callable` is inadequate to express.

The fix is "easy" but weird! :sweat_smile: 
```python
class _RetrieverFunc(typing.Protocol):
    def __call__(self, uri: str) -> referencing.Resource[Schema]:
        ...

def create_retrieve_callable(parsers: ParserSet) -> _RetrieverFunc:
    # body unchanged
```

Between the two, it feels difficult to setup what feel -- at first -- like relatively simple annotations to pass. As I said above, given that `pyright` can follow the `_attrs` module in `referencing`, I'm inclined to think that's a `mypy` bug or missing feature. And `pyright` is picky, but in a way that feels tolerable to use and correct.

The last issue I have is with `pyright`'s type matching rules, so I might be wrong about how to solve this or whether or not it should be allowed, but I found that I had to import `referencing.jsonschema.Schema` to satisfy types. (You may have noticed this usage above.)
I tried setting up a recursive TypeAlias to describe JSON datatypes, and using that
```python
JsonPrimitive: t.TypeAlias = t.Union[int, float, str, bool, None]
JsonElement: t.TypeAlias = t.Union[JsonPrimitive, "JsonList", "JsonDict"]
JsonList: t.TypeAlias = t.List[JsonElement]
JsonDict: t.TypeAlias = t.Dict[str, JsonElement]

JsonSchema: t.TypeAlias = JsonDict | bool
```

But `pyright` doesn't like `Resource[JsonSchema]` because it doesn't match against `Resource[Schema]`.
I think it would work if I used the exact value in `Schema` of `bool | Mapping[str, Any]`, but no other type will pass because `Resource` is invariant in its type variable.

So my final note (long issue report, sorry!) is that I'm probably going to be importing `Schema` on the assumption that it's safe to rely on that name and using it to ensure that my annotations always match `referencing`. If we can adjust the variance of `Resource` to be looser, that might make it easier to apply a narrower type.

**Comment by Julian** [comment]
Thanks for the detailed issue, which I haven't read through fully yet :D -- but because it seems like it may at least be slightly related, I also can't figure out why newer versions of pyright seem to have issues with type invariance either! I have it pinned to `1.1.307` here in the repo's noxfile which is the newest working version. Newer versions complain about things which make no sense to me, though I've only spent a few minutes trying to poke at them.

I'll have a closer look at the rest of what you shared after the weekend, thanks for writing it up.

**Comment by Julian** [comment]
(Will probably repeatedly respond to this in piecemeal as I flip back and forth between looking at it and some other things) -- 

> mypy doesn't understand that retrieve is an attrs-provided field:

I remember fighting with this a bit -- I think mypy doesn't understand `dataclass_transform` yet or something, specifically it doesn't understand [`attrs`' `alias` argument](https://www.attrs.org/en/stable/init.html#private-attributes-and-aliases) -- and vice versa, pyright is slightly dumb and doesn't understand that the alias argument isn't needed at all when all it's doing is automatic renaming of private attributes, so you *have* to write `alias` even when it's not needed.
More type checker time wasting, grumble grumble.

> I'm probably going to be importing Schema on the assumption that it's safe to rely on that name and using it to ensure that my annotations always match referencing

`referencing.jsonschema.Schema` is definitely public -- lemme know if there's some other convention in the typing community to make that even more obvious. For that matter, so is [`referencing.jsonschema.SchemaRegistry`](https://referencing.readthedocs.io/en/stable/api/#referencing.jsonschema.SchemaRegistry) which I figured would be even more common to use, it's just `Registry[Schema]` specializing the generic to something JSON Schema specific (as opposed to future support for OpenAPI or something).

**Comment by Julian** [comment]
So -- I think given that the mypy part of this is partly or in whole a "known issue" with mypy -- namely python/mypy#5406 -- and given the last comment about indeed using the public objects for pyright -- I'm going to close this perhaps.

Obviously speak up if you disagree, or if you have concrete suggestions for what to tweak, as should anyone else running into trouble here.

But yeah on the mypy side specifically I'm not sure if there's anything to do until things are fixed upstream.

**Comment by sirosen** [comment]
Yep, I'm happy with that! (Well, in as much as I'm happy with the type checkers...)

The only part of this, on review, that I might keep an eye on is "how should we support that fancy recursive JSON type"? It's clearly a subtype of `Mapping[str, Any]` and it feels like it should work. But I don't need that but at all for my work -- it just felt more correct academically.
