### ISSUE TITLE
RefResolutionError when using self signed certificate

### ISSUE THREAD

**Issue by vitofly** [python-jsonschema/referencing#8]
jsonschema.exceptions.RefResolutionError: HTTPSConnectionPool(host='xxxxx.xxxx.xxxx', port=443): Max retries exceeded with url: /schema.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

https://github.com/python-jsonschema/jsonschema/blob/main/jsonschema/validators.py#L993
Could you please allow users to pass CA_BUNDLE path to verify parameter in requests.get() method?
e.g.   result = requests.get(uri, verify='/path/to/certfile').json()

**Comment by Julian** [comment]
Hello there!

This, along with many many other `$ref`-related issues, is now finally being handled in python-jsonschema/jsonschema#1049 with the introduction of this new [referencing library](https://github.com/python-jsonschema/referencing/) which is fully compliant and has APIs which I hope are a lot easier to understand and customize.  (In case you didn't notice, at some point I transferred this issue between repositories).

The next release of `jsonschema` (v4.18.0) will contain a merged version of that PR, and should be released shortly in beta, and followed quickly by a regular release, assuming no critical issues are reported.

`referencing` will indeed allow you to make HTTP requests however you'd like to do so, including by using a client which allows self-signed certificates if you must do so. If you still care to, I'd love it if you tried out the beta once it is released, or certainly it'd be hugely helpful to immediately install the branch containing this work (https://github.com/python-jsonschema/jsonschema/tree/referencing) and confirm. You can in the interim find documentation for the change in a [preview page here](https://python-jsonschema--1049.org.readthedocs.build/en/1049/referencing/) -- a section specifically for hooking in HTTP clients is [here](https://python-jsonschema--1049.org.readthedocs.build/en/1049/referencing/#automatically-retrieving-resources-over-http) and feedback is definitely welcome.

I'm going to close this given it indeed seems like it is addressed by python-jsonschema/jsonschema#1049, but feel free to follow up with any comments. Sorry for the delay in getting to these, but hopefully this new release will bring lots of benefit!
