### ISSUE TITLE
Potential issue with attrs==22.1.0

### ISSUE THREAD

**Issue by jkhenning** [python-jsonschema/referencing#99]
(report originating [here](https://github.com/allegroai/clearml/issues/1153))

It seems that in some cases, using `attrs==22.1.0` with `referencing` raises this on import:
```
>> import referencing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.8/site-packages/referencing/__init__.py", line 4, in <module>
    from referencing._core import Anchor, Registry, Resource, Specification
  File ".../lib/python3.8/site-packages/referencing/_core.py", line 29, in <module>
    class Specification(Generic[D]):
  File ".../lib/python3.8/site-packages/referencing/_core.py", line 55, in Specification
    ] = field(alias="anchors_in")
TypeError: field() got an unexpected keyword argument 'alias'
```

No such error is raised when using `attrs==22.2.0`.

Looking at the `attrs` source code for the `22.1.0` tag, the `alias` argument is not available in all overrides for the `field()` function. Specifically, the `attrs` [change log](https://www.attrs.org/en/stable/changelog.html#id2) for version 22.2.0 states that "`attrs.field()` now supports an alias option for explicit `__init__` argument names." which basically implies that there's no full  support of that in previous versions.

I would suggest raising the `attrs` dependency to `>=22.2.0`

**Comment by Julian** [comment]
referencing [already declares it depends on `22.2.0`](https://github.com/python-jsonschema/referencing/blob/main/pyproject.toml#L37) so this would normally point to user (installation) error. Would love to hear a way to reproduce if not.

**Comment by jkhenning** [comment]
@Julian apologies, you're right. For some reason it seems that pip resolution ended up installing 22.1.0... :(
